//
//  StudentLocation.swift
//  OnTheMap
//
//  Created by Victor Guerra on 03/06/15.
//  Copyright (c) 2015 Victor Guerra. All rights reserved.
//

import Foundation

struct StudentLocation : Printable {
    // Parse autogenerated id
    let objectId : String?
    // Udacity account user id
    let uniqueKey : String
    // first and last names
    let firstName : String
    let lastName : String
    // human-readable address 
    let mapString : String
    // URL provided by Student
    let mediaURL : String
    // geographic coordinates
    let latitude : Float
    let longitude : Float
    // creation and update dates
    let createdAt : NSDate
    let updatedAt : NSDate
    // conforming to Printable Protocol
    var description : String {
        return ""
    }
    
    init (dict : [String : AnyObject]) {
        objectId = dict[APIClient.StudentLocationKey.objectId] as? String
        lastName = dict[APIClient.StudentLocationKey.lastName] as! String
        firstName = dict[APIClient.StudentLocationKey.firstName] as! String
        uniqueKey = dict[APIClient.StudentLocationKey.uniqueKey] as! String
        mapString = dict[APIClient.StudentLocationKey.mapString] as! String
        mediaURL = dict[APIClient.StudentLocationKey.mediaURL] as! String
        latitude = dict[APIClient.StudentLocationKey.latitude] as! Float
        longitude = dict[APIClient.StudentLocationKey.longitude] as! Float
        
        // For the time being we just fill in this dates with the
        // current date
        createdAt = NSDate()
        updatedAt = NSDate()
    }
    
    static func arrayFromDictionaries(results: [[String:AnyObject]]) -> [StudentLocation] {
        var locations = [StudentLocation]()
        for result in results {
            locations.append(StudentLocation(dict: result))
        }
        return locations
    }

}

